gpu: 0
batch_size: 10
num_runs: 1
save_dir: ./results
name: demo
wandb: False
save_samples: True
save_traj: False
save_traj_raw_data: False
show_eval: False
eval_fn_list: ['psnr', 'lpips']
task_group: pixel  # pixel, sd, or latent
project_name: 'DAPS'
seed: 42